version: '3.8'
services:
  mongo:
    image: docker-registry.sabay.com/docker/official/mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Lyeng12345
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '12'
          memory: 65536M
    volumes:
      - /var/database-data/39674920/mongo/67c13d8041e91447e8d1fb63:/data/db
    networks:
      mysabay-39674920:
        aliases:
          - 405opl4gm7oa7xm5.mongodb.sabay.com
  dbgate:
    image: docker-registry.sabay.com/docker/official/dbgate/dbgate:production
    environment:
      CONNECTIONS: mongo
      LABEL_mongo: MongoDB
      SERVER_mongo: 405opl4gm7oa7xm5.mongodb.sabay.com
      PASSWORD_MODE_mongo: askUser
      ENGINE_mongo: mongo@dbgate-plugin-mongo
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=cloud-public
        - traefik.http.routers.405opl4gm7oa7xm5-mongo.entrypoints=websecure
        - >-
          traefik.http.routers.405opl4gm7oa7xm5-mongo.rule=Host(`405opl4gm7oa7xm4.kosalkan.com`)
        - traefik.http.routers.405opl4gm7oa7xm5-mongo.tls=true
        - >-
          traefik.http.services.405opl4gm7oa7xm5-mongo.loadbalancer.server.port=3000
        - >-
          traefik.http.services.405opl4gm7oa7xm5-mongo.loadbalancer.passhostheader=true
    networks:
      proxy: null
      mysabay-39674920:
        aliases:
          - 405opl4gm7oa7xm4.kosalkan.com
networks:
  mysabay-39674920:
    external: true
  proxy:
    external: true
