version: "3"
services:
  pdns:
    #build: pdns
    image: pschiffe/pdns-mysql
    hostname: pdns
    domainname: samplepowerdns.com
    container_name: powerdns-api.local
    restart: always
    ports:
      - "54:5"
      - "54:54/udp"
      - "8081:8081"
    environment:
      - PDNS_gmysql_host=mysql
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=root
      - PDNS_gmysql_dbname=powerdnsadmin
      - PDNS_gmysql_password=rootPassword
      # - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=eqjkwleuiy8yhhdhjasjdkakji9uy
      - PDNSCONF_API_KEY=eqjkwleuiy8yhhdhjasjdkakji9uy
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24,192.168.65.1/32
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret2
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=1500
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1
    networks:
      - sabay_docker

networks:
  sabay_docker:
    external: true