version: "3.8"
services:
  pdns:
    image: pschiffe/pdns-mysql
    container_name: pdns
    restart: unless-stopped
    ports:
      - "53:53/tcp"  # DNS over TCP
      - "53:53/udp"  # DNS over UDP
      - "8081:8081"  # PowerDNS API or web interface
    environment:
      PDNS_gmysql_host: host.docker.internal  # Address to access MySQL
      PDNS_gmysql_port: 3306  # MySQL port
      PDNS_gmysql_user: powerdns  # User created in MySQL
      PDNS_gmysql_password: powerdnsPassword  # Password for the user
      PDNS_gmysql_dbname: powerdnsadmin  # Database name
      PDNS_api: "yes"
      PDNS_api_key: eqjkwleuiy8yhhdhjasjdkakji9uy
      PDNS_webserver: "yes"
      PDNS_webserver_address: "0.0.0.0"  # Allows connections from any IP address
      PDNS_webserver_password: secret2
      PDNS_webserver-allow-from: 0.0.0.0/0  # Allows all IPs to access the web interface
    networks:
      - sabay_docker

networks:
  sabay_docker:
    external: true
