version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.20.2
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - sabay_docker

# volumes:
#   portainer_data:

networks:
  sabay_docker:
    external: true
