version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.20.2
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      - sabay_docker

  pdns-admin:
    image: powerdnsadmin/powerdns-admin:latest
    environment:
      - DATABASE_URL=mysql://powerdnsuser:powerdnsPassword@your_mysql_host/powerdns  # Update with your MySQL host, user, password, and DB name
      - FLASK_APP=powerdns-admin.py
      - PDNS_API_URL=http://your_pdns_host:8081/api/v1/servers/localhost  # Update with your PowerDNS host address
      - PDNS_API_KEY=your_api_key  # Replace with your actual API key
    ports:
      - "8081:8080"
    networks:
      - sabay_docker
    depends_on:
      - portainer
    restart: always

networks:
  sabay_docker:
    external: true
