version: "3.8"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: chiev.lyeng
      MYSQL_PASSWORD: Lyeng12345
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

    networks:
      - sabay_docker

volumes:
  mysql_data:

networks:
  sabay_docker:
    external: true
