version: '3.8'
services:
  app:
    image: docker-registry.sabay.com/docker/haproxy:latest
    networks:
      - mysabay-39674920
      - proxy
    configs:
      - source: mysabay-39674920-my_domain_stack_app
        target: /usr/local/etc/haproxy/haproxy.cfg
        mode: 644
    deploy:
      update_config:
        order: start-first
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: none
        delay: 5s
        max_attempts: 5
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.docker.network=proxy
        - traefik.constraint-label=cloud-public
        - >-
          traefik.http.routers.mysabay-39674920-my_domain_stack_app-websecure.entrypoints=http
        - >-
          traefik.http.routers.mysabay-39674920-my_domain_stack_app-websecure.rule=Host("app-405gzrlkm5z73p3v.master.mysabay.com")
        - >-
          traefik.http.routers.mysabay-39674920-my_domain_stack_app-websecure.tls=false
        - >-
          traefik.http.services.mysabay-39674920-my_domain_stack_app.loadbalancer.server.port=80
        - >-
          traefik.http.services.mysabay-39674920-my_domain_stack_app.loadbalancer.passhostheader=true
networks:
  mysabay-39674920:
    external: true
  proxy:
    external: true
configs:
  mysabay-39674920-my_domain_stack_app:
    external: true
