version: "3.8"

services:
  minio:
    image: minio/minio:latest
    # image: docker-registry.sabay.com/docker/official/minio/minio:latest
    container_name: minio
    ports:
      - "9002:9002" # API access
      - "9001:9001" # Web UI access
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - ./minio_data:/data
    command: server --console-address ":9001" /data

volumes:
  minio_data:
