version: "3.8"
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - sabay_docker

volumes:
  redis_data:

networks:
  sabay_docker:
    external: true
